### PR TITLE
Setup CD

### PR DESCRIPTION
**Pull request by NotMyFault**
@guysoft Make sure you have the following secrets at https://github.com/jenkinsci/configurationslicing-plugin/settings/secrets/actions before merging. But considering the RPU PR has been merged, it should all be set up.
 

Make sure to put an "interesting label" like `feature` or `enhancement` on this and the other PR so CD can pick it up. 

I've addressed the inconsistency of tabs and spaces in the pom as well.

### CODE REVIEW

**Comment by guysoft** [comment]
Checked and its there.  Thanks for all the help"

**Comment by NotMyFault** [comment]
You forgot the labels of the PRs 👀

**Comment by guysoft** [comment]
You mean this one or all current ones?

**Comment by NotMyFault** [comment]
I meant this and my other one. Release drafter does only do releases if content is merged that may be interested for the user.
Otherwise you would always have new releases for dependency updates e.g.

**Pull request merged**
