### PR TITLE
JENKINS-34190: Added new boolean slicer for editing the 'Build whenev…

### PR DESCRIPTION
**Pull request by bischoje**
…er a SNAPSHOT dependency is built' build trigger on Maven projects. Also added a unit test for the slicer.

### CODE REVIEW

**Comment by bischoje** [comment]
I have built the code in my fork and installed in on my company's main Jenkins server. We tested the new boolean slicer today and it worked well. Hopefully this can help someone else too.

**Comment by mgaunin** [comment]
Hi Jeff,
May I ask you to move your test class under `maven` package please?
You can also manage the deprecated `MavenModuleSet(String name)` constructor with `MavenModuleSet mavenModuleSet = new MavenModuleSet(Jenkins.getInstance(),"mock");`
Thanks
Mikael

**Comment by bischoje** [comment]
Okay thanks, I'll make those changes.

**Comment by guysoft** [comment]
@bischoje Hey, have the changes you mentioned you will do been made in the end?
I have recently adopted this plugin and trying to make sense of what PRs to pull.

**Comment by bischoje** [comment]
Hey guy! Looking back, I'm not sure if I ever made those changes. I changed jobs the same month that this message was posted. It's likely that I forgot. 

It's up to you whether you want to consider this PR. It adds a tiny feature that my team found useful at the time. Let me know if you still want me to make updates to it.

**Comment by guysoft** [comment]
Now that 1.50 has been released can consider this.
@bischoje I think if you have the time adding @mgaunin 's suggestion https://github.com/jenkinsci/configurationslicing-plugin/pull/18#issuecomment-302442185 would make me pull this for sure. Otherwise I am a little hesitant.

**Comment by bischoje** [comment]
Hey @guysoft, I updated the branch but now the checks are failing (the build does succeed locally though). 

The error appears to be:

> No test report files were found. Configuration error?

Maybe I need to merge master into my branch to get it in sync? What do you suggest?

**Comment by guysoft** [comment]
I think its failing because spotbugs, which I disabled in build. Merge and prey.

**Pull request merged**
