### PR TITLE
Apply OpenRewrite recipes RemoveDependencyVersionOverride and AddOrModernizeJenkinsFile

### PR DESCRIPTION
**Pull request by gounthar**
Hello `configurationslicing` developers!

This is an automated pull request created by the [Jenkins Plugin Modernizer](https://github.com/jenkinsci/plugin-modernizer-tool) tool. The tool has applied the following recipes to modernize the plugin:

<details>
    <summary>Add Jenkinsfile</summary>
    <p><em>io.jenkins.tools.pluginmodernizer.AddOrModernizeJenkinsFile</em></p>
    <blockquote>Updates Jenkinsfile to build with recommended Java versions, platforms, and settings, or creates the file if absent. Also upgrades to a newer parent version, as the new version of the Jenkinsfille uses JDK17 and JDK21.</blockquote>
</details>

<details>
    <summary>Add dependency check</summary>
    <p><em>io.jenkins.tools.pluginmodernizer.AddDependencyCheck</em></p>
    <blockquote>Adds a dependabot GitHub action to the plugin repository</blockquote>
</details>

<details>
    <summary>Add plugins BOM</summary>
    <p><em>io.jenkins.tools.pluginmodernizer.AddPluginsBom</em></p>
    <blockquote>Add the Jenkins BOM to the dependenciesManagement section of the pom.xml.
</blockquote>
</details>

<details>
    <summary>Upgrade parent version</summary>
    <p><em>io.jenkins.tools.pluginmodernizer.UpgradeParentVersion</em></p>
    <blockquote>Upgrade the parent version to latest available</blockquote>
</details>

<details>
    <summary>Remove dependency version override</summary>
    <p><em>io.jenkins.tools.pluginmodernizer.RemoveDependencyVersionOverride</em></p>
    <blockquote>Remove dependencies version override if managed from parent or bom</blockquote>
</details>

<details>
    <summary>Remove extra maven properties</summary>
    <p><em>io.jenkins.tools.pluginmodernizer.RemoveExtraMavenProperties</em></p>
    <blockquote>Remove extra maven properties from the pom</blockquote>
</details>

<details>
    <summary>Migrate from Java 11 to Java 17</summary>
    <p><em>io.jenkins.tools.pluginmodernizer.UpgradeToJava17</em></p>
    <blockquote>Migrate from Java 11 to Java 17</blockquote>
</details>

<details>
    <summary>Add Jenkinsfile</summary>
    <p><em>io.jenkins.tools.pluginmodernizer.AddOrModernizeJenkinsFile</em></p>
    <blockquote>Updates Jenkinsfile to build with recommended Java versions, platforms, and settings, or creates the file if absent. Also upgrades to a newer parent version, as the new version of the Jenkinsfille uses JDK17 and JDK21.</blockquote>
</details>

<details>
    <summary>Add dependency check</summary>
    <p><em>io.jenkins.tools.pluginmodernizer.AddDependencyCheck</em></p>
    <blockquote>Adds a dependabot GitHub action to the plugin repository</blockquote>
</details>

<details>
    <summary>Upgrade to latest recommended core version and ensure the bom is matching the core version</summary>
    <p><em>io.jenkins.tools.pluginmodernizer.UpgradeToRecommendCoreVersion</em></p>
    <blockquote>Upgrade to latest recommended core version and ensure the bom is matching the core version</blockquote>
</details>

<details>
    <summary>Convert JUnit 4 TestCase to JUnit Jupiter</summary>
    <p><em>io.jenkins.tools.pluginmodernizer.MigrateJUnitTestCase</em></p>
    <blockquote>Convert JUnit 4 TestCase to JUnit Jupiter</blockquote>
</details>

### CODE REVIEW

**Comment by guysoft** [comment]
Any reason not to merge this?

**Comment by MarkEWaite** [comment]
> Any reason not to merge this?

The odd placement of the end of comment in the Jenkinsfile is a little distracting to me and the removal of the `forkCount` setting is also a little distracting, since it will increase the total time for plugin jobs on ci.jenkins.io, but neither of those are worth blocking the pull request.

I've rephrased the pull request title so that it mentions what was changed rather than listing all the recipes that were applied. I think that users want to know about the changes.

**Comment by gounthar** [comment]
I apologize, I should have been more careful and created draft pull requests instead of "real" pull requests using our tool.

To improve the experience, I will add a feature request to list only in the title the recipes that produced different outputs. The current lengthy list can be quite overwhelming, even though the changes were minimal.

Thank you for merging this pull request despite its flaws, Mark.

**Comment by gounthar** [comment]
I apologize, I should have been more careful and created draft pull requests instead of "real" pull requests using our tool.

To improve the experience, I will add a feature request to list only in the title the recipes that produced different outputs. The current lengthy list can be quite overwhelming, even though the changes were minimal.

Thank you for merging this pull request despite its flaws, Mark.

**Comment by MarkEWaite** [comment]
@gounthar no problem.  Happy to have the pull request.  I've applied a change to the Jenkinsfile formatting to make it consistent with the plugin archetype.  Thanks for the improvement!

**Comment by gounthar** [comment]
Thanks a lot, @MarkEWaite .
I opened [an issue](https://github.com/jenkinsci/plugin-modernizer-tool/issues/371) to track that strange formatting issue.

**Pull request merged**
